"""Stress tests for coordination controllers (no API calls).

Run: python stress_test_coordination.py [--runs RUN1 RUN2 ...]   (default run: window600_high)

Scores the LLM champions and the baselines under conditions the test bed
normally leaves out, on the development and held-out batteries (the sealed
test battery is not used):
- nominal: reference;
- noise_1mm / noise_3mm: Gaussian noise on all four level measurements;
- mismatch_a / mismatch_b: every plant parameter (outlet areas a1-a4, pump
  gains k1/k2, valve splits) scaled by a seeded draw in [0.9, 1.1] in the
  simulated plant only, so every controller's built-in model is off; the
  draws are listed in the summary;
- analyser: the production value in the telemetry is 60 s late and updated
  every 30 s, like a particle-size analyser;
- fault_h3_nan: the h3 reading the supervisor sees is NaN from t = 400 s
  (the safety wrapper then holds the setpoints);
- fault_h4_stuck / fault_production_stuck: that reading freezes at t = 400 s.

Writes results/coordination/stress_tests.csv (per controller, condition and
scenario) and results/coordination/stress_tests.md (summary).
"""

import argparse
import csv
import dataclasses
import os
from concurrent.futures import ProcessPoolExecutor

import numpy as np

import four_tank_coordination as C
from mpc_supervisor import MPCSupervisor, tuned_params
from supervisor_security import safe_exec_supervisor

OUT_DIR = os.path.join("results", "coordination")
SUPERVISORS_DIR = "generated_supervisors_coordination"
MISMATCH_PARAMS = ("a1", "a2", "a3", "a4", "k1", "k2", "gamma_1", "gamma_2")


def _mismatch(seed):
    rng = np.random.default_rng(seed)
    return tuple((name, round(float(rng.uniform(0.9, 1.1)), 4)) for name in MISMATCH_PARAMS)


CONDITIONS = {
    "nominal": {},
    "noise_1mm": {"sensor_noise_std": 0.001},
    "noise_3mm": {"sensor_noise_std": 0.003},
    "mismatch_a": {"plant_scale": _mismatch(11)},
    "mismatch_b": {"plant_scale": _mismatch(12)},
    "analyser": {"production_delay_s": 60.0, "production_hold_s": 30.0},
    "fault_h3_nan": {"telemetry_faults": (("h3", "nan", 400.0),)},
    "fault_h4_stuck": {"telemetry_faults": (("h4", "stuck", 400.0),)},
    "fault_production_stuck": {"telemetry_faults": (("production", "stuck", 400.0),)},
}


def _controller(name, sources):
    if name == "fixed_recipe":
        return C.fixed_recipe_supervisor
    if name == "mpc_untuned":
        return MPCSupervisor()
    if name == "mpc_tuned":
        return MPCSupervisor(**tuned_params())
    fn, err = safe_exec_supervisor(sources[name])
    if err:
        raise RuntimeError(f"{name}: {err}")
    return fn


def _run(job):
    name, condition, battery, scenario, sources = job
    timeout = 10.0 if name.startswith("mpc") else scenario.supervisor_timeout_s
    scenario = dataclasses.replace(scenario, supervisor_timeout_s=timeout, **CONDITIONS[condition])
    m = C.run_episode(_controller(name, sources), scenario)["metrics"]
    return {"controller": name, "condition": condition, "battery": battery, "scenario": scenario.name,
            "kind": scenario.kind_label, **m, "score": C.score(m)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", nargs="*", default=["window600_high"])
    args = ap.parse_args()
    sources = {}
    for run in args.runs:
        with open(os.path.join(SUPERVISORS_DIR, run, "current_supervisor.py"), "r", encoding="utf-8") as f:
            sources[run] = f.read()
    controllers = list(args.runs) + ["fixed_recipe", "mpc_untuned", "mpc_tuned"]
    batteries = {"dev": C.make_battery("dev", 3, 1), "heldout": C.make_battery("dev", 3, 2)}
    jobs = [(name, cond, b, sc, sources) for name in controllers for cond in CONDITIONS
            for b, scen in batteries.items() for sc in scen]
    with ProcessPoolExecutor(max_workers=max(1, (os.cpu_count() or 2) - 1)) as pool:
        rows = list(pool.map(_run, jobs, chunksize=4))

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "stress_tests.csv"), "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    mean = lambda name, cond, key="score": float(np.mean([r[key] for r in rows if r["controller"] == name
                                                          and r["condition"] == cond]))
    lines = ["# Coordination stress tests", "",
             "Mean score over the development and held-out batteries (84 scenarios; lower is better), and the "
             "change against the same controller without stress. Generated by `stress_test_coordination.py`.", "",
             "| Condition | " + " | ".join(f"`{c}`" for c in controllers) + " |",
             "|---|" + "---|" * len(controllers)]
    for cond in CONDITIONS:
        cells = []
        for name in controllers:
            value, base = mean(name, cond), mean(name, "nominal")
            cells.append(f"{value:.1f}" if cond == "nominal" else f"{value:.1f} ({100 * (value / base - 1):+.0f} %)")
        lines.append(f"| {cond} | " + " | ".join(cells) + " |")
    lines += ["", "Safety-wrapper interventions and exceptions (totals over the 84 scenarios):", "",
              "| Condition | " + " | ".join(f"`{c}`" for c in controllers) + " |",
              "|---|" + "---|" * len(controllers)]
    for cond in CONDITIONS:
        cells = [f"{int(84 * mean(n, cond, 'wrapper_interventions'))} / {int(84 * mean(n, cond, 'exceptions'))}"
                 for n in controllers]
        lines.append(f"| {cond} | " + " | ".join(cells) + " |")
    lines += ["", "Plant-parameter factors (simulated plant only):", ""]
    for cond in ("mismatch_a", "mismatch_b"):
        lines.append(f"- {cond}: " + ", ".join(f"{k} x{v}" for k, v in CONDITIONS[cond]["plant_scale"]))
    with open(os.path.join(OUT_DIR, "stress_tests.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
